# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af86d09dc090a517797d6398c62f22f36f777532c8dcf51f939c894e52763143d437cc448438cc215c56331fba4fb7ad448244c75483bcbcfbcdf9aedbac1d3

test:
  secret_key_base: 67dc0bc4d3c663d8463c58d542aa13327b0d1bd5ed775cbcd4b9f71cadbb5e514c7b04f3840ad3cc9f55406f7cc89175648d1055e14c651b3d026608e51d7f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
